### ISSUE TITLE
Fix the commands to run client and server side tests and generate Instanbul reports

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#154]

**Comment by nevinsjr** [comment]
Yeah, you can add a custom command to the scripts section of the
package.json to run both of them.  As far as coverage goes, I am not sure;
I haven;t looked up how to run istanbul on our Angular tests yet.

**Comment by JoshuaVSherman** [comment]
This would be nice to have for our report out to professor next week, do
you want me or you to figure this out?

On Mon, Jul 4, 2016 at 9:28 AM, nevinsjr <notifications@github.com> wrote:

> Yeah, you can add a custom command to the scripts section of the
> package.json to run both of them. As far as coverage goes, I am not sure;
> I haven;t looked up how to run istanbul on our Angular tests yet.
>
> On Mon, Jul 4, 2016 at 6:48 AM Josh Sherman <notifications@github.com>
> wrote:
>
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/PennStateSoftwareTest/FinalProjectPennState/issues/154
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AFI0nqS2vI-QRaVMVFWGbR9R_WdWETY3ks5qSQENgaJpZM4JEVzb
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PennStateSoftwareTest/FinalProjectPennState/issues/154#issuecomment-230290809>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMuN2IpX7CHlOES1WeYQsBP4dyCNvMHWks5qSQp4gaJpZM4JEVzb>
> .
>



-- 
Josh Sherman
www.joshandmariamusic.com

**Comment by nevinsjr** [comment]
You can take a crack at it if you would like.

**Comment by JoshuaVSherman** [comment]
Mina, please add this to the test plan @habibmn09
