### ISSUE TITLE
As a venue manager, I need to see a central list of the bands

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#157]
Acceptance Criteria:
Web page displays a list of the bands from the database.

**Comment by habibmn09** [comment]
what do we need to update?

**Comment by JoshuaVSherman** [comment]
The .env file

**Comment by JoshuaVSherman** [comment]
the diagrams are out of date, please look at the app and code to determine updates where needed

**Comment by JoshuaVSherman** [comment]
some of the diagrams were not correct to begin with, and I left comments for you to correct them, many weeks ago, but you did nothing
