### ISSUE TITLE
Complete Angular 2 Hero App Tutorial

### ISSUE THREAD

**Issue by nevinsjr** [PennStateSoftwareTest/FinalProjectPennState#16]
https://angular.io/docs/ts/latest/tutorial/

**Comment by nevinsjr** [comment]
Complete.  I uploaded the source to the Google Drive for reference by the group.

**Comment by JoshuaVSherman** [comment]
awesome, you need to teach the rest of us. I will work on this same tutorial next week, but you are the expert!
