### ISSUE TITLE
make all of the current Angular2 routes work from within the single dashboard as child notes to the same internal page frame

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#178]

**Comment by JoshuaVSherman** [comment]
Need help understanding this and adding to SRS

**Comment by nevinsjr** [comment]
Does this help?

https://docs.google.com/presentation/d/1lgeSc8P_BPiXCeaTDjxbCuzVvC0Q6Zf-pUC3Wup-a1k/edit#slide=id.p

**Comment by JoshuaVSherman** [comment]
yep, thanks

On Mon, Jul 11, 2016 at 7:14 PM, nevinsjr <notifications@github.com> wrote:

> Does this help?
>
>
> https://docs.google.com/presentation/d/1lgeSc8P_BPiXCeaTDjxbCuzVvC0Q6Zf-pUC3Wup-a1k/edit#slide=id.p
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/PennStateSoftwareTest/FinalProjectPennState/issues/178#issuecomment-231893264>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMuN2MdfeFaWB7akLwtWlrvc89xr9mAwks5qUs5KgaJpZM4JIgMQ>
> .
>



-- 
Josh Sherman
www.joshandmariamusic.com
