### ISSUE TITLE
Determine if we have time to implement a Foundation CSS UI in Phase I or Not?

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#18]

**Comment by nevinsjr** [comment]
This isn't a story.

**Comment by JoshuaVSherman** [comment]
This is a task, determine if we can implement Foundation responsive UI framework or not during the time we have for phase I

**Comment by nevinsjr** [comment]
We do.  I've already made it a part of the development environment.  I was going to explain that yesterday, but you didn't want to hear anything about the dev environment I configured.

**Comment by JoshuaVSherman** [comment]
Um, I thought you were not available, and needed to leave after 20 minutes?

Are you okay? You seem aggravated

 

I am just now trying to work on the development environment, and I have like all of these emails from you, so I’m sorry that my timing is not your timing on this project!

**Comment by JoshuaVSherman** [comment]
ok great, the last discussion we had, was that we might need to take this out of scope for phase I, so that is why i had this task, great.
