### ISSUE TITLE
The test for delete user passes but does not delete the user from the test database

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#184]

**Comment by nevinsjr** [comment]
I ran the test by itself really quick, and it looks like the test runs before the connection with the database is established:

/usr/local/bin/node ./node_modules/mocha/bin/mocha --recursive -w

[?25lListening on port 3000...


  userService delete unit test
    ✓ should return 200 - deleted account with email foo@bar.com


  1 passing (67ms)

scrs db opened

**Comment by nevinsjr** [comment]
Ok, fix is up.
