### ISSUE TITLE
Create and upload the task sheet - end of Sprint 5 for Sprint 6

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#22]
Acceptance criteria: submit pdf to Angel by sunday prior to meeting

**Comment by JoshuaVSherman** [comment]
Include what features we are going to demo to the professor and practice the demo before we have the meeting this time

**Comment by JoshuaVSherman** [comment]
Need to write the task sheet, who is going to write it this time?

**Comment by nevinsjr** [comment]
It's my turn, so I can do that.
