### ISSUE TITLE
Resolve error deploying to Heroku

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#25]

**Comment by JoshuaVSherman** [comment]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 5.11.1...
       Using default npm version: 3.8.6
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)
       
       > team6finalproject@1.0.0 postinstall /tmp/build_35f987622da477e118e7a1b4e561081b/PennStateSoftwareTest-FinalProjectPennState-f862e0c
       > typings install
       
       sh: 1: typings: not found
       
       npm ERR! Linux 3.13.0-85-generic
       npm ERR! argv "/tmp/build_35f987622da477e118e7a1b4e561081b/PennStateSoftwareTest-FinalProjectPennState-f862e0c/.heroku/node/bin/node" "/tmp/build_35f987622da477e118e7a1b4e561081b/PennStateSoftwareTest-FinalProjectPennState-f862e0c/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_35f987622da477e118e7a1b4e561081b/PennStateSoftwareTest-FinalProjectPennState-f862e0c/.npmrc"
       npm ERR! node v5.11.1
       npm ERR! npm  v3.8.6
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! team6finalproject@1.0.0 postinstall: `typings install`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the team6finalproject@1.0.0 postinstall script 'typings install'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the team6finalproject package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     typings install
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs team6finalproject
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls team6finalproject
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_35f987622da477e118e7a1b4e561081b/PennStateSoftwareTest-FinalProjectPennState-f862e0c/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app

**Comment by nevinsjr** [comment]
Looks like it is calling typings install before npm install, so it is
trying to call typings install before it has the typings binary.

**Comment by JoshuaVSherman** [comment]
It would help if I just follow the setup instructions

I’ll get this done soon, shouldn’t be a problem :)

**Comment by JoshuaVSherman** [comment]
https://devcenter.heroku.com/articles/troubleshooting-node-deploys

**Comment by nevinsjr** [comment]
Did you Google it?  They require an "engine" property to specify the
version of node we are using, so you should probably start with that.

**Comment by JoshuaVSherman** [comment]
Yo, yo

Already did dat

 

Still failing,

Lemme keep trying first before I ping you

 

 

 

Josh Sherman

 

 <http://www.joshandmariamusic.com/> www.joshandmariamusic.com

 

for bookings

 <mailto:bookings@joshandmariamusic.com> bookings@joshandmariamusic.com

**Comment by JoshuaVSherman** [comment]
i set the engine but it is still failing, there is something else going on here

**Comment by nevinsjr** [comment]
ok cool.  if you hit a brick wall, we could push it off until next week.
 that way, we don;t get too far behind on code.  We can always demo from a
local environment.

**Comment by nevinsjr** [comment]
same log message?

**Comment by JoshuaVSherman** [comment]
yep

 

I’m I get blocked, I’ll move on to Angular

No prob

It is all good

I’m have fun, no worries  :)

 

Did you see the new logo?

**Comment by nevinsjr** [comment]
ok, cool.  i would hate for you to be frustrated. gal it is fun.  No, I
haven't! I'll look now.

**Comment by JoshuaVSherman** [comment]
Also I have really good phone skills for the ‘talk to a human’ if it comes to that with Heroku

They want our business and will help if I say so

**Comment by nevinsjr** [comment]
The new logo is slick

**Comment by JoshuaVSherman** [comment]
Its pretty good

I’ve asked for some lighting effects

**Comment by JoshuaVSherman** [comment]
I also defined a color pallet

I’ll send it to you

**Comment by nevinsjr** [comment]
Perfect.  We may have to download a custom version of Foundation instead of
using the one i installed with Bower... let's talk about it tomorrow
morning (in case I don;t make it to the meeting tonight).

**Comment by JoshuaVSherman** [comment]
https://thawing-falls-50722.herokuapp.com/
I have pushed this getting started tutorial app to our heroku account

**Comment by nevinsjr** [comment]
No worries.  We'll get the build straight for Heroku.

**Comment by JoshuaVSherman** [comment]
I’m still having fun

and at least I know that Heroku is where we want to be

since I also tried other alternatives

 

Josh

**Comment by JoshuaVSherman** [comment]
John and I worked on this issue this morning, and John fixed it after finding where the stinking log files were being displayed!!
