### ISSUE TITLE
Define the UIs for authentication, band / musician, booking agent / venue profile data forms

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#5]

**Comment by nevinsjr** [comment]
This will be a part of the stories themselves.

**Comment by JoshuaVSherman** [comment]
I would like to keep this as a task for myself, please leave this one open and in the backlog

**Comment by nevinsjr** [comment]
I would prefer you used your own board or list for personal things.

**Comment by JoshuaVSherman** [comment]
This is not personal, this is related to our project

For personal items I use the Cozi app

 

Josh
