### ISSUE TITLE
As a user, I can create a new account, log in, and log out

### ISSUE THREAD

**Issue by nevinsjr** [PennStateSoftwareTest/FinalProjectPennState#51]
Acceptance Criteria:
New user form accepts password and e-mail address.
New user form offers selection of Band Manager or Venue Manager account types.
New user form validates email for uniqueness
Service validates email address uniqueness.

**Comment by nevinsjr** [comment]
I broke the rules by assigning a point value without the team... we will re-estimate later.  I just wanted to have something to show the professor this evening.

**Comment by JoshuaVSherman** [comment]
Just break the rules, Assign points this sprint, we can change them later,
we are interative

**Comment by nevinsjr** [comment]
Most recent commit updates to use e-mail as username. @habibmn09 the test plan would need to reflect that.

**Comment by JoshuaVSherman** [comment]
removed this from the acceptance criteria and submitted work item 236

"New user form validates email for uniqueness"
