### ISSUE TITLE
trying to use GitHub Wiki, unable to get images to display

### ISSUE THREAD

**Issue by JoshuaVSherman** [PennStateSoftwareTest/FinalProjectPennState#79]
I need some help using the GitHub Wiki, if that is where we are going to do our detailed designs and developer notes, for example, I wanted to put a procedure for setting up development environment on Ubuntu, but was unable to get the images (screenshots) to display. I'm tired and calling it quits for tonight.

**Comment by JoshuaVSherman** [comment]
I put the files here that I want as a Wiki, file:///C:/Users/SHup/Google%20Drive/AdvancedSoftwareEngStudio/figures/Wikis/Webstorm%20and%20NodeJS%20on%20Utuntu%20Desktop%20Notes.htm

**Comment by nevinsjr** [comment]
Does this work?

https://help.github.com/articles/adding-images-to-wikis/

**Comment by JoshuaVSherman** [comment]
If you want to put graphics in the Wiki, then they have to already be on the internet. The Wiki does not allow you to upload any graphics or attachments. Therefore, any developer notes that I create, having screenshots will be placed in our Drive folder. Talk to you this evening.
